version: "3.8"

services:
  # MongoDB database
  mongodb:
    image: mongo:7.0
    container_name: form-app-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: form-app
    volumes:
      - mongodb_data:/data/db
    networks:
      - form-app-network

  # Backend API
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: form-app-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password@mongodb:27017/form-app?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-here
      CORS_ORIGIN: http://localhost:3000
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      # Email configuration (optional)
      ENABLE_EMAIL_NOTIFICATIONS: "false"
      # SMTP_HOST: smtp.gmail.com
      # SMTP_PORT: 587
      # SMTP_USER: your-email@gmail.com
      # SMTP_PASS: your-app-password
      # FROM_EMAIL: your-email@gmail.com
      # FROM_NAME: Form App
    volumes:
      - ./apps/backend/uploads:/app/uploads
      # For development - mount source code
      - ./apps/backend/src:/app/src
    depends_on:
      - mongodb
    networks:
      - form-app-network

  # Frontend (for development)
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: form-app-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    volumes:
      # For development - mount source code
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - form-app-network

volumes:
  mongodb_data:

networks:
  form-app-network:
    driver: bridge
